// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppInfo():Promise<main.AppConfig|main.SessionView>;

export function CreateAccount(arg1:number):Promise<main.AccountView>;

export function CreateCard(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.CardView>;

export function CreateTransaction(arg1:main.TransactionInput):Promise<main.TransactionView>;

export function DeleteAccount(arg1:string):Promise<void>;

export function DeleteCard(arg1:string):Promise<void>;

export function DeleteTransaction(arg1:string):Promise<void>;

export function DeleteUser(arg1:string):Promise<void>;

export function GetAccount(arg1:string):Promise<main.AccountView>;

export function GetCard(arg1:string):Promise<main.CardView>;

export function GetProfile():Promise<main.UserView>;

export function GetTransaction(arg1:string):Promise<main.TransactionView>;

export function GetUser(arg1:string):Promise<main.UserView>;

export function ListAccounts():Promise<Array<main.AccountView>>;

export function ListCards():Promise<Array<main.CardView>>;

export function ListTransactions():Promise<Array<main.TransactionView>>;

export function ListUsers():Promise<Array<main.UserView>>;

export function Login(arg1:string,arg2:string):Promise<main.SessionView>;

export function Logout():Promise<void>;

export function RefreshSession():Promise<main.SessionView>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<main.SessionView>;

export function UpdateAccount(arg1:string,arg2:number):Promise<main.AccountView>;

export function UpdateCard(arg1:string,arg2:main.UpdateCardInput):Promise<main.CardView>;

export function UpdateCardStatus(arg1:string,arg2:boolean):Promise<main.CardView>;

export function UpdateTransaction(arg1:string,arg2:main.TransactionUpdateInput):Promise<main.TransactionView>;

export function UpdateUserEmail(arg1:string,arg2:string):Promise<main.UserView>;

export function UpdateUserPassword(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateUserStatus(arg1:string,arg2:boolean):Promise<main.UserView>;
