// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function CreateAccount(arg1) {
  return window['go']['main']['App']['CreateAccount'](arg1);
}

export function CreateCard(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateCard'](arg1, arg2, arg3, arg4);
}

export function CreateTransaction(arg1) {
  return window['go']['main']['App']['CreateTransaction'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteCard(arg1) {
  return window['go']['main']['App']['DeleteCard'](arg1);
}

export function DeleteTransaction(arg1) {
  return window['go']['main']['App']['DeleteTransaction'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function GetAccount(arg1) {
  return window['go']['main']['App']['GetAccount'](arg1);
}

export function GetCard(arg1) {
  return window['go']['main']['App']['GetCard'](arg1);
}

export function GetProfile() {
  return window['go']['main']['App']['GetProfile']();
}

export function GetTransaction(arg1) {
  return window['go']['main']['App']['GetTransaction'](arg1);
}

export function GetUser(arg1) {
  return window['go']['main']['App']['GetUser'](arg1);
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function ListCards() {
  return window['go']['main']['App']['ListCards']();
}

export function ListTransactions() {
  return window['go']['main']['App']['ListTransactions']();
}

export function ListUsers() {
  return window['go']['main']['App']['ListUsers']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function RefreshSession() {
  return window['go']['main']['App']['RefreshSession']();
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}

export function UpdateAccount(arg1, arg2) {
  return window['go']['main']['App']['UpdateAccount'](arg1, arg2);
}

export function UpdateCard(arg1, arg2) {
  return window['go']['main']['App']['UpdateCard'](arg1, arg2);
}

export function UpdateCardStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateCardStatus'](arg1, arg2);
}

export function UpdateTransaction(arg1, arg2) {
  return window['go']['main']['App']['UpdateTransaction'](arg1, arg2);
}

export function UpdateUserEmail(arg1, arg2) {
  return window['go']['main']['App']['UpdateUserEmail'](arg1, arg2);
}

export function UpdateUserPassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateUserPassword'](arg1, arg2, arg3);
}

export function UpdateUserStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateUserStatus'](arg1, arg2);
}
